Achat:
    type: entity
    table: achat
    indexes:
        fk_achat_evenement1_idx:
            columns:
                - evenement
        fk_achat_acheteur1_idx:
            columns:
                - acheteur
        fk_achat_categorie1_idx:
            columns:
                - categorie
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        objet:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        prix:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        date:
            type: datetime
            nullable: false
            comment: ''
    manyToOne:
        categorie:
            targetEntity: Categorie
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                categorie:
                    referencedColumnName: id
            orphanRemoval: false
        acheteur:
            targetEntity: Personne
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                acheteur:
                    referencedColumnName: id
            orphanRemoval: false
        evenement:
            targetEntity: Evenement
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                evenement:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        personne:
            targetEntity: Personne
            cascade: {  }
            mappedBy: achat
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
