Personne:
    type: entity
    table: personne
    indexes:
        fk_personne_evenement1_idx:
            columns:
                - evenement
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        prenom:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        partdefaut:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
    manyToOne:
        evenement:
            targetEntity: Evenement
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                evenement:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        achat:
            targetEntity: Achat
            cascade: {  }
            mappedBy: null
            inversedBy: personne
            joinTable:
                name: beneficiaire
                joinColumns:
                    -
                        name: personne
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: achat
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
