site_kidoikoiaki_homepage:
    path:     /
    defaults: { _controller: SiteKidoikoiakiBundle:Home:index }

site_kidoikoiaki_event:
    path:     /evenement/{token}
    defaults: { _controller: SiteKidoikoiakiBundle:Event:index }