site_kidoikoiaki_homepage:
    path:     /
    defaults: { _controller: SiteKidoikoiakiBundle:Home:index }

site_kidoikoiaki_participants:
    path:     /participants/{token}
    defaults: { _controller: SiteKidoikoiakiBundle:Home:participants }

site_kidoikoiaki_spending:
    path:     /depenses/{token}
    defaults: { _controller: SiteKidoikoiakiBundle:Home:depenses }

site_kidoikoiaki_assessment:
    path:     /bilan/{token}
    defaults: { _controller: SiteKidoikoiakiBundle:Home:bilan }

site_kidoikoiaki_create_event:
    path:     /evenement
    defaults: { _controller: SiteKidoikoiakiBundle:Evenement:index }