services:
#    site_kidoikoiaki.example:
#        class: Site\KidoikoiakiBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    evenement_service:
        class: Site\KidoikoiakiBundle\Services\EvenementService
        arguments: ["@doctrine.orm.entity_manager"]